export const MOCK_DATA = {
    "total_count": 2016425,
    "incomplete_results": false,
    "items": [
      {
        "id": 28457823,
        "node_id": "MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==",
        "name": "freeCodeCamp",
        "full_name": "freeCodeCamp/freeCodeCamp",
        "private": false,
        "owner": {
          "login": "freeCodeCamp",
          "id": 9892522,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/9892522?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/freeCodeCamp",
          "html_url": "https://github.com/freeCodeCamp",
          "followers_url": "https://api.github.com/users/freeCodeCamp/followers",
          "following_url": "https://api.github.com/users/freeCodeCamp/following{/other_user}",
          "gists_url": "https://api.github.com/users/freeCodeCamp/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/freeCodeCamp/subscriptions",
          "organizations_url": "https://api.github.com/users/freeCodeCamp/orgs",
          "repos_url": "https://api.github.com/users/freeCodeCamp/repos",
          "events_url": "https://api.github.com/users/freeCodeCamp/events{/privacy}",
          "received_events_url": "https://api.github.com/users/freeCodeCamp/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/freeCodeCamp/freeCodeCamp",
        "description": "freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
        "fork": false,
        "url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp",
        "forks_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/forks",
        "keys_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/teams",
        "hooks_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/hooks",
        "issue_events_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/events{/number}",
        "events_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/events",
        "assignees_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/assignees{/user}",
        "branches_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/branches{/branch}",
        "tags_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/tags",
        "blobs_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/languages",
        "stargazers_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/stargazers",
        "contributors_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contributors",
        "subscribers_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscribers",
        "subscription_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscription",
        "commits_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contents/{+path}",
        "compare_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/merges",
        "archive_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/downloads",
        "issues_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues{/number}",
        "pulls_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/labels{/name}",
        "releases_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/releases{/id}",
        "deployments_url": "https://api.github.com/repos/freeCodeCamp/freeCodeCamp/deployments",
        "created_at": "2014-12-24T17:49:19Z",
        "updated_at": "2024-01-13T07:29:50Z",
        "pushed_at": "2024-01-13T04:58:57Z",
        "git_url": "git://github.com/freeCodeCamp/freeCodeCamp.git",
        "ssh_url": "git@github.com:freeCodeCamp/freeCodeCamp.git",
        "clone_url": "https://github.com/freeCodeCamp/freeCodeCamp.git",
        "svn_url": "https://github.com/freeCodeCamp/freeCodeCamp",
        "homepage": "http://contribute.freecodecamp.org/",
        "size": 401294,
        "stargazers_count": 381257,
        "watchers_count": 381257,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 35426,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 356,
        "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause \"New\" or \"Revised\" License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "careers",
          "certification",
          "community",
          "curriculum",
          "d3",
          "education",
          "freecodecamp",
          "hacktoberfest",
          "javascript",
          "learn-to-code",
          "math",
          "nodejs",
          "nonprofits",
          "programming",
          "react",
          "teachers"
        ],
        "visibility": "public",
        "forks": 35426,
        "open_issues": 356,
        "watchers": 381257,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 10270250,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
        "name": "react",
        "full_name": "facebook/react",
        "private": false,
        "owner": {
          "login": "facebook",
          "id": 69631,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
          "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/facebook",
          "html_url": "https://github.com/facebook",
          "followers_url": "https://api.github.com/users/facebook/followers",
          "following_url": "https://api.github.com/users/facebook/following{/other_user}",
          "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
          "organizations_url": "https://api.github.com/users/facebook/orgs",
          "repos_url": "https://api.github.com/users/facebook/repos",
          "events_url": "https://api.github.com/users/facebook/events{/privacy}",
          "received_events_url": "https://api.github.com/users/facebook/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/facebook/react",
        "description": "The library for web and native user interfaces.",
        "fork": false,
        "url": "https://api.github.com/repos/facebook/react",
        "forks_url": "https://api.github.com/repos/facebook/react/forks",
        "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/facebook/react/teams",
        "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
        "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
        "events_url": "https://api.github.com/repos/facebook/react/events",
        "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
        "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
        "tags_url": "https://api.github.com/repos/facebook/react/tags",
        "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/facebook/react/languages",
        "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
        "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
        "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
        "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
        "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
        "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/facebook/react/merges",
        "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
        "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
        "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
        "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
        "deployments_url": "https://api.github.com/repos/facebook/react/deployments",
        "created_at": "2013-05-24T16:15:54Z",
        "updated_at": "2024-01-13T08:12:38Z",
        "pushed_at": "2024-01-12T22:27:24Z",
        "git_url": "git://github.com/facebook/react.git",
        "ssh_url": "git@github.com:facebook/react.git",
        "clone_url": "https://github.com/facebook/react.git",
        "svn_url": "https://github.com/facebook/react",
        "homepage": "https://react.dev",
        "size": 368471,
        "stargazers_count": 217289,
        "watchers_count": 217289,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 45796,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1568,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "declarative",
          "frontend",
          "javascript",
          "library",
          "react",
          "ui"
        ],
        "visibility": "public",
        "forks": 45796,
        "open_issues": 1568,
        "watchers": 217289,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 11730342,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTczMDM0Mg==",
        "name": "vue",
        "full_name": "vuejs/vue",
        "private": false,
        "owner": {
          "login": "vuejs",
          "id": 6128107,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjYxMjgxMDc=",
          "avatar_url": "https://avatars.githubusercontent.com/u/6128107?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/vuejs",
          "html_url": "https://github.com/vuejs",
          "followers_url": "https://api.github.com/users/vuejs/followers",
          "following_url": "https://api.github.com/users/vuejs/following{/other_user}",
          "gists_url": "https://api.github.com/users/vuejs/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/vuejs/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/vuejs/subscriptions",
          "organizations_url": "https://api.github.com/users/vuejs/orgs",
          "repos_url": "https://api.github.com/users/vuejs/repos",
          "events_url": "https://api.github.com/users/vuejs/events{/privacy}",
          "received_events_url": "https://api.github.com/users/vuejs/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/vuejs/vue",
        "description": "This is the repo for Vue 2. For Vue 3, go to https://github.com/vuejs/core",
        "fork": false,
        "url": "https://api.github.com/repos/vuejs/vue",
        "forks_url": "https://api.github.com/repos/vuejs/vue/forks",
        "keys_url": "https://api.github.com/repos/vuejs/vue/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/vuejs/vue/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/vuejs/vue/teams",
        "hooks_url": "https://api.github.com/repos/vuejs/vue/hooks",
        "issue_events_url": "https://api.github.com/repos/vuejs/vue/issues/events{/number}",
        "events_url": "https://api.github.com/repos/vuejs/vue/events",
        "assignees_url": "https://api.github.com/repos/vuejs/vue/assignees{/user}",
        "branches_url": "https://api.github.com/repos/vuejs/vue/branches{/branch}",
        "tags_url": "https://api.github.com/repos/vuejs/vue/tags",
        "blobs_url": "https://api.github.com/repos/vuejs/vue/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/vuejs/vue/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/vuejs/vue/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/vuejs/vue/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/vuejs/vue/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/vuejs/vue/languages",
        "stargazers_url": "https://api.github.com/repos/vuejs/vue/stargazers",
        "contributors_url": "https://api.github.com/repos/vuejs/vue/contributors",
        "subscribers_url": "https://api.github.com/repos/vuejs/vue/subscribers",
        "subscription_url": "https://api.github.com/repos/vuejs/vue/subscription",
        "commits_url": "https://api.github.com/repos/vuejs/vue/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/vuejs/vue/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/vuejs/vue/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/vuejs/vue/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/vuejs/vue/contents/{+path}",
        "compare_url": "https://api.github.com/repos/vuejs/vue/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/vuejs/vue/merges",
        "archive_url": "https://api.github.com/repos/vuejs/vue/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/vuejs/vue/downloads",
        "issues_url": "https://api.github.com/repos/vuejs/vue/issues{/number}",
        "pulls_url": "https://api.github.com/repos/vuejs/vue/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/vuejs/vue/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/vuejs/vue/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/vuejs/vue/labels{/name}",
        "releases_url": "https://api.github.com/repos/vuejs/vue/releases{/id}",
        "deployments_url": "https://api.github.com/repos/vuejs/vue/deployments",
        "created_at": "2013-07-29T03:24:51Z",
        "updated_at": "2024-01-13T08:08:14Z",
        "pushed_at": "2024-01-12T10:29:00Z",
        "git_url": "git://github.com/vuejs/vue.git",
        "ssh_url": "git@github.com:vuejs/vue.git",
        "clone_url": "https://github.com/vuejs/vue.git",
        "svn_url": "https://github.com/vuejs/vue",
        "homepage": "http://v2.vuejs.org",
        "size": 32316,
        "stargazers_count": 206120,
        "watchers_count": 206120,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 34649,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 607,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "framework",
          "frontend",
          "javascript",
          "vue"
        ],
        "visibility": "public",
        "forks": 34649,
        "open_issues": 607,
        "watchers": 206120,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 126577260,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMjY1NzcyNjA=",
        "name": "javascript-algorithms",
        "full_name": "trekhleb/javascript-algorithms",
        "private": false,
        "owner": {
          "login": "trekhleb",
          "id": 3000285,
          "node_id": "MDQ6VXNlcjMwMDAyODU=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3000285?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/trekhleb",
          "html_url": "https://github.com/trekhleb",
          "followers_url": "https://api.github.com/users/trekhleb/followers",
          "following_url": "https://api.github.com/users/trekhleb/following{/other_user}",
          "gists_url": "https://api.github.com/users/trekhleb/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/trekhleb/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/trekhleb/subscriptions",
          "organizations_url": "https://api.github.com/users/trekhleb/orgs",
          "repos_url": "https://api.github.com/users/trekhleb/repos",
          "events_url": "https://api.github.com/users/trekhleb/events{/privacy}",
          "received_events_url": "https://api.github.com/users/trekhleb/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/trekhleb/javascript-algorithms",
        "description": "📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings",
        "fork": false,
        "url": "https://api.github.com/repos/trekhleb/javascript-algorithms",
        "forks_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/forks",
        "keys_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/teams",
        "hooks_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/hooks",
        "issue_events_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/events",
        "assignees_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/tags",
        "blobs_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/languages",
        "stargazers_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/stargazers",
        "contributors_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/contributors",
        "subscribers_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/subscribers",
        "subscription_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/subscription",
        "commits_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/merges",
        "archive_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/downloads",
        "issues_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/labels{/name}",
        "releases_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/deployments",
        "created_at": "2018-03-24T07:47:04Z",
        "updated_at": "2024-01-13T07:58:06Z",
        "pushed_at": "2024-01-11T10:25:08Z",
        "git_url": "git://github.com/trekhleb/javascript-algorithms.git",
        "ssh_url": "git@github.com:trekhleb/javascript-algorithms.git",
        "clone_url": "https://github.com/trekhleb/javascript-algorithms.git",
        "svn_url": "https://github.com/trekhleb/javascript-algorithms",
        "homepage": "",
        "size": 13363,
        "stargazers_count": 179167,
        "watchers_count": 179167,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 29571,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 349,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "algorithm",
          "algorithms",
          "computer-science",
          "data-structures",
          "interview",
          "interview-preparation",
          "javascript",
          "javascript-algorithms"
        ],
        "visibility": "public",
        "forks": 29571,
        "open_issues": 349,
        "watchers": 179167,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 14440270,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNDQ0MDI3MA==",
        "name": "You-Dont-Know-JS",
        "full_name": "getify/You-Dont-Know-JS",
        "private": false,
        "owner": {
          "login": "getify",
          "id": 150330,
          "node_id": "MDQ6VXNlcjE1MDMzMA==",
          "avatar_url": "https://avatars.githubusercontent.com/u/150330?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/getify",
          "html_url": "https://github.com/getify",
          "followers_url": "https://api.github.com/users/getify/followers",
          "following_url": "https://api.github.com/users/getify/following{/other_user}",
          "gists_url": "https://api.github.com/users/getify/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/getify/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/getify/subscriptions",
          "organizations_url": "https://api.github.com/users/getify/orgs",
          "repos_url": "https://api.github.com/users/getify/repos",
          "events_url": "https://api.github.com/users/getify/events{/privacy}",
          "received_events_url": "https://api.github.com/users/getify/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/getify/You-Dont-Know-JS",
        "description": "A book series on JavaScript. @YDKJS on twitter.",
        "fork": false,
        "url": "https://api.github.com/repos/getify/You-Dont-Know-JS",
        "forks_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/forks",
        "keys_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/teams",
        "hooks_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/hooks",
        "issue_events_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/issues/events{/number}",
        "events_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/events",
        "assignees_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/assignees{/user}",
        "branches_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/branches{/branch}",
        "tags_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/tags",
        "blobs_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/languages",
        "stargazers_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/stargazers",
        "contributors_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/contributors",
        "subscribers_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/subscribers",
        "subscription_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/subscription",
        "commits_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/contents/{+path}",
        "compare_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/merges",
        "archive_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/downloads",
        "issues_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/issues{/number}",
        "pulls_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/labels{/name}",
        "releases_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/releases{/id}",
        "deployments_url": "https://api.github.com/repos/getify/You-Dont-Know-JS/deployments",
        "created_at": "2013-11-16T02:37:24Z",
        "updated_at": "2024-01-13T05:29:46Z",
        "pushed_at": "2024-01-12T17:40:47Z",
        "git_url": "git://github.com/getify/You-Dont-Know-JS.git",
        "ssh_url": "git@github.com:getify/You-Dont-Know-JS.git",
        "clone_url": "https://github.com/getify/You-Dont-Know-JS.git",
        "svn_url": "https://github.com/getify/You-Dont-Know-JS",
        "homepage": "",
        "size": 12837,
        "stargazers_count": 174195,
        "watchers_count": 174195,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 33422,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 127,
        "license": {
          "key": "other",
          "name": "Other",
          "spdx_id": "NOASSERTION",
          "url": null,
          "node_id": "MDc6TGljZW5zZTA="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "async",
          "book",
          "book-series",
          "closures",
          "education",
          "es2015",
          "es6",
          "javascript",
          "learn-to-code",
          "programming",
          "prototypes",
          "training-materials",
          "training-providers"
        ],
        "visibility": "public",
        "forks": 33422,
        "open_issues": 127,
        "watchers": 174195,
        "default_branch": "2nd-ed",
        "score": 1.0
      },
      {
        "id": 2126244,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMTI2MjQ0",
        "name": "bootstrap",
        "full_name": "twbs/bootstrap",
        "private": false,
        "owner": {
          "login": "twbs",
          "id": 2918581,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjI5MTg1ODE=",
          "avatar_url": "https://avatars.githubusercontent.com/u/2918581?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/twbs",
          "html_url": "https://github.com/twbs",
          "followers_url": "https://api.github.com/users/twbs/followers",
          "following_url": "https://api.github.com/users/twbs/following{/other_user}",
          "gists_url": "https://api.github.com/users/twbs/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/twbs/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/twbs/subscriptions",
          "organizations_url": "https://api.github.com/users/twbs/orgs",
          "repos_url": "https://api.github.com/users/twbs/repos",
          "events_url": "https://api.github.com/users/twbs/events{/privacy}",
          "received_events_url": "https://api.github.com/users/twbs/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/twbs/bootstrap",
        "description": "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.",
        "fork": false,
        "url": "https://api.github.com/repos/twbs/bootstrap",
        "forks_url": "https://api.github.com/repos/twbs/bootstrap/forks",
        "keys_url": "https://api.github.com/repos/twbs/bootstrap/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/twbs/bootstrap/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/twbs/bootstrap/teams",
        "hooks_url": "https://api.github.com/repos/twbs/bootstrap/hooks",
        "issue_events_url": "https://api.github.com/repos/twbs/bootstrap/issues/events{/number}",
        "events_url": "https://api.github.com/repos/twbs/bootstrap/events",
        "assignees_url": "https://api.github.com/repos/twbs/bootstrap/assignees{/user}",
        "branches_url": "https://api.github.com/repos/twbs/bootstrap/branches{/branch}",
        "tags_url": "https://api.github.com/repos/twbs/bootstrap/tags",
        "blobs_url": "https://api.github.com/repos/twbs/bootstrap/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/twbs/bootstrap/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/twbs/bootstrap/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/twbs/bootstrap/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/twbs/bootstrap/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/twbs/bootstrap/languages",
        "stargazers_url": "https://api.github.com/repos/twbs/bootstrap/stargazers",
        "contributors_url": "https://api.github.com/repos/twbs/bootstrap/contributors",
        "subscribers_url": "https://api.github.com/repos/twbs/bootstrap/subscribers",
        "subscription_url": "https://api.github.com/repos/twbs/bootstrap/subscription",
        "commits_url": "https://api.github.com/repos/twbs/bootstrap/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/twbs/bootstrap/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/twbs/bootstrap/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/twbs/bootstrap/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/twbs/bootstrap/contents/{+path}",
        "compare_url": "https://api.github.com/repos/twbs/bootstrap/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/twbs/bootstrap/merges",
        "archive_url": "https://api.github.com/repos/twbs/bootstrap/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/twbs/bootstrap/downloads",
        "issues_url": "https://api.github.com/repos/twbs/bootstrap/issues{/number}",
        "pulls_url": "https://api.github.com/repos/twbs/bootstrap/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/twbs/bootstrap/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/twbs/bootstrap/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/twbs/bootstrap/labels{/name}",
        "releases_url": "https://api.github.com/repos/twbs/bootstrap/releases{/id}",
        "deployments_url": "https://api.github.com/repos/twbs/bootstrap/deployments",
        "created_at": "2011-07-29T21:19:00Z",
        "updated_at": "2024-01-13T02:46:21Z",
        "pushed_at": "2024-01-11T21:55:06Z",
        "git_url": "git://github.com/twbs/bootstrap.git",
        "ssh_url": "git@github.com:twbs/bootstrap.git",
        "clone_url": "https://github.com/twbs/bootstrap.git",
        "svn_url": "https://github.com/twbs/bootstrap",
        "homepage": "https://getbootstrap.com",
        "size": 238610,
        "stargazers_count": 166413,
        "watchers_count": 166413,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": true,
        "forks_count": 79162,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 528,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "bootstrap",
          "css",
          "css-framework",
          "html",
          "javascript",
          "sass",
          "scss"
        ],
        "visibility": "public",
        "forks": 79162,
        "open_issues": 528,
        "watchers": 166413,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 88011908,
        "node_id": "MDEwOlJlcG9zaXRvcnk4ODAxMTkwOA==",
        "name": "project-based-learning",
        "full_name": "practical-tutorials/project-based-learning",
        "private": false,
        "owner": {
          "login": "practical-tutorials",
          "id": 89421154,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjg5NDIxMTU0",
          "avatar_url": "https://avatars.githubusercontent.com/u/89421154?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/practical-tutorials",
          "html_url": "https://github.com/practical-tutorials",
          "followers_url": "https://api.github.com/users/practical-tutorials/followers",
          "following_url": "https://api.github.com/users/practical-tutorials/following{/other_user}",
          "gists_url": "https://api.github.com/users/practical-tutorials/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/practical-tutorials/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/practical-tutorials/subscriptions",
          "organizations_url": "https://api.github.com/users/practical-tutorials/orgs",
          "repos_url": "https://api.github.com/users/practical-tutorials/repos",
          "events_url": "https://api.github.com/users/practical-tutorials/events{/privacy}",
          "received_events_url": "https://api.github.com/users/practical-tutorials/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/practical-tutorials/project-based-learning",
        "description": "Curated list of project-based tutorials",
        "fork": false,
        "url": "https://api.github.com/repos/practical-tutorials/project-based-learning",
        "forks_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/forks",
        "keys_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/teams",
        "hooks_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/hooks",
        "issue_events_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/issues/events{/number}",
        "events_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/events",
        "assignees_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/assignees{/user}",
        "branches_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/branches{/branch}",
        "tags_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/tags",
        "blobs_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/languages",
        "stargazers_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/stargazers",
        "contributors_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/contributors",
        "subscribers_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/subscribers",
        "subscription_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/subscription",
        "commits_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/contents/{+path}",
        "compare_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/merges",
        "archive_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/downloads",
        "issues_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/issues{/number}",
        "pulls_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/labels{/name}",
        "releases_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/releases{/id}",
        "deployments_url": "https://api.github.com/repos/practical-tutorials/project-based-learning/deployments",
        "created_at": "2017-04-12T05:07:46Z",
        "updated_at": "2024-01-13T08:16:17Z",
        "pushed_at": "2024-01-08T04:12:12Z",
        "git_url": "git://github.com/practical-tutorials/project-based-learning.git",
        "ssh_url": "git@github.com:practical-tutorials/project-based-learning.git",
        "clone_url": "https://github.com/practical-tutorials/project-based-learning.git",
        "svn_url": "https://github.com/practical-tutorials/project-based-learning",
        "homepage": null,
        "size": 438,
        "stargazers_count": 149355,
        "watchers_count": 149355,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 20148,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 96,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "beginner-project",
          "cpp",
          "golang",
          "javascript",
          "project",
          "python",
          "tutorial",
          "webdevelopment"
        ],
        "visibility": "public",
        "forks": 20148,
        "open_issues": 96,
        "watchers": 149355,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 6498492,
        "node_id": "MDEwOlJlcG9zaXRvcnk2NDk4NDky",
        "name": "javascript",
        "full_name": "airbnb/javascript",
        "private": false,
        "owner": {
          "login": "airbnb",
          "id": 698437,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5ODQzNw==",
          "avatar_url": "https://avatars.githubusercontent.com/u/698437?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/airbnb",
          "html_url": "https://github.com/airbnb",
          "followers_url": "https://api.github.com/users/airbnb/followers",
          "following_url": "https://api.github.com/users/airbnb/following{/other_user}",
          "gists_url": "https://api.github.com/users/airbnb/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/airbnb/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/airbnb/subscriptions",
          "organizations_url": "https://api.github.com/users/airbnb/orgs",
          "repos_url": "https://api.github.com/users/airbnb/repos",
          "events_url": "https://api.github.com/users/airbnb/events{/privacy}",
          "received_events_url": "https://api.github.com/users/airbnb/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/airbnb/javascript",
        "description": "JavaScript Style Guide",
        "fork": false,
        "url": "https://api.github.com/repos/airbnb/javascript",
        "forks_url": "https://api.github.com/repos/airbnb/javascript/forks",
        "keys_url": "https://api.github.com/repos/airbnb/javascript/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/airbnb/javascript/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/airbnb/javascript/teams",
        "hooks_url": "https://api.github.com/repos/airbnb/javascript/hooks",
        "issue_events_url": "https://api.github.com/repos/airbnb/javascript/issues/events{/number}",
        "events_url": "https://api.github.com/repos/airbnb/javascript/events",
        "assignees_url": "https://api.github.com/repos/airbnb/javascript/assignees{/user}",
        "branches_url": "https://api.github.com/repos/airbnb/javascript/branches{/branch}",
        "tags_url": "https://api.github.com/repos/airbnb/javascript/tags",
        "blobs_url": "https://api.github.com/repos/airbnb/javascript/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/airbnb/javascript/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/airbnb/javascript/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/airbnb/javascript/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/airbnb/javascript/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/airbnb/javascript/languages",
        "stargazers_url": "https://api.github.com/repos/airbnb/javascript/stargazers",
        "contributors_url": "https://api.github.com/repos/airbnb/javascript/contributors",
        "subscribers_url": "https://api.github.com/repos/airbnb/javascript/subscribers",
        "subscription_url": "https://api.github.com/repos/airbnb/javascript/subscription",
        "commits_url": "https://api.github.com/repos/airbnb/javascript/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/airbnb/javascript/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/airbnb/javascript/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/airbnb/javascript/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/airbnb/javascript/contents/{+path}",
        "compare_url": "https://api.github.com/repos/airbnb/javascript/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/airbnb/javascript/merges",
        "archive_url": "https://api.github.com/repos/airbnb/javascript/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/airbnb/javascript/downloads",
        "issues_url": "https://api.github.com/repos/airbnb/javascript/issues{/number}",
        "pulls_url": "https://api.github.com/repos/airbnb/javascript/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/airbnb/javascript/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/airbnb/javascript/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/airbnb/javascript/labels{/name}",
        "releases_url": "https://api.github.com/repos/airbnb/javascript/releases{/id}",
        "deployments_url": "https://api.github.com/repos/airbnb/javascript/deployments",
        "created_at": "2012-11-01T23:13:50Z",
        "updated_at": "2024-01-13T07:46:42Z",
        "pushed_at": "2024-01-10T06:16:38Z",
        "git_url": "git://github.com/airbnb/javascript.git",
        "ssh_url": "git@github.com:airbnb/javascript.git",
        "clone_url": "https://github.com/airbnb/javascript.git",
        "svn_url": "https://github.com/airbnb/javascript",
        "homepage": null,
        "size": 3619,
        "stargazers_count": 139951,
        "watchers_count": 139951,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 26574,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 164,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "arrow-functions",
          "es2015",
          "es2016",
          "es2017",
          "es2018",
          "es6",
          "eslint",
          "javascript",
          "linting",
          "naming-conventions",
          "style-guide",
          "style-linter",
          "styleguide",
          "tc39"
        ],
        "visibility": "public",
        "forks": 26574,
        "open_issues": 164,
        "watchers": 139951,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 112507086,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTI1MDcwODY=",
        "name": "30-seconds-of-code",
        "full_name": "Chalarangelo/30-seconds-of-code",
        "private": false,
        "owner": {
          "login": "Chalarangelo",
          "id": 8281875,
          "node_id": "MDQ6VXNlcjgyODE4NzU=",
          "avatar_url": "https://avatars.githubusercontent.com/u/8281875?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Chalarangelo",
          "html_url": "https://github.com/Chalarangelo",
          "followers_url": "https://api.github.com/users/Chalarangelo/followers",
          "following_url": "https://api.github.com/users/Chalarangelo/following{/other_user}",
          "gists_url": "https://api.github.com/users/Chalarangelo/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Chalarangelo/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Chalarangelo/subscriptions",
          "organizations_url": "https://api.github.com/users/Chalarangelo/orgs",
          "repos_url": "https://api.github.com/users/Chalarangelo/repos",
          "events_url": "https://api.github.com/users/Chalarangelo/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Chalarangelo/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/Chalarangelo/30-seconds-of-code",
        "description": "Short code snippets for all your development needs",
        "fork": false,
        "url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code",
        "forks_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/forks",
        "keys_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/teams",
        "hooks_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/hooks",
        "issue_events_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/events",
        "assignees_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/tags",
        "blobs_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/languages",
        "stargazers_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/stargazers",
        "contributors_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/contributors",
        "subscribers_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/subscribers",
        "subscription_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/subscription",
        "commits_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/merges",
        "archive_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/downloads",
        "issues_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/labels{/name}",
        "releases_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/deployments",
        "created_at": "2017-11-29T17:35:03Z",
        "updated_at": "2024-01-13T07:15:41Z",
        "pushed_at": "2024-01-12T18:27:12Z",
        "git_url": "git://github.com/Chalarangelo/30-seconds-of-code.git",
        "ssh_url": "git@github.com:Chalarangelo/30-seconds-of-code.git",
        "clone_url": "https://github.com/Chalarangelo/30-seconds-of-code.git",
        "svn_url": "https://github.com/Chalarangelo/30-seconds-of-code",
        "homepage": "https://30secondsofcode.org/",
        "size": 622924,
        "stargazers_count": 117465,
        "watchers_count": 117465,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 12121,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "cc-by-4.0",
          "name": "Creative Commons Attribution 4.0 International",
          "spdx_id": "CC-BY-4.0",
          "url": "https://api.github.com/licenses/cc-by-4.0",
          "node_id": "MDc6TGljZW5zZTI1"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "astro",
          "awesome-list",
          "css",
          "education",
          "es6-javascript",
          "git",
          "github-actions",
          "html",
          "javascript",
          "learn-to-code",
          "learning-resources",
          "netlify",
          "nodejs",
          "programming",
          "python",
          "reactjs",
          "snippets",
          "snippets-collection",
          "website-infrastructure"
        ],
        "visibility": "public",
        "forks": 12121,
        "open_issues": 0,
        "watchers": 117465,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 9384267,
        "node_id": "MDEwOlJlcG9zaXRvcnk5Mzg0MjY3",
        "name": "electron",
        "full_name": "electron/electron",
        "private": false,
        "owner": {
          "login": "electron",
          "id": 13409222,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDA5MjIy",
          "avatar_url": "https://avatars.githubusercontent.com/u/13409222?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/electron",
          "html_url": "https://github.com/electron",
          "followers_url": "https://api.github.com/users/electron/followers",
          "following_url": "https://api.github.com/users/electron/following{/other_user}",
          "gists_url": "https://api.github.com/users/electron/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/electron/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/electron/subscriptions",
          "organizations_url": "https://api.github.com/users/electron/orgs",
          "repos_url": "https://api.github.com/users/electron/repos",
          "events_url": "https://api.github.com/users/electron/events{/privacy}",
          "received_events_url": "https://api.github.com/users/electron/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/electron/electron",
        "description": ":electron: Build cross-platform desktop apps with JavaScript, HTML, and CSS",
        "fork": false,
        "url": "https://api.github.com/repos/electron/electron",
        "forks_url": "https://api.github.com/repos/electron/electron/forks",
        "keys_url": "https://api.github.com/repos/electron/electron/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/electron/electron/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/electron/electron/teams",
        "hooks_url": "https://api.github.com/repos/electron/electron/hooks",
        "issue_events_url": "https://api.github.com/repos/electron/electron/issues/events{/number}",
        "events_url": "https://api.github.com/repos/electron/electron/events",
        "assignees_url": "https://api.github.com/repos/electron/electron/assignees{/user}",
        "branches_url": "https://api.github.com/repos/electron/electron/branches{/branch}",
        "tags_url": "https://api.github.com/repos/electron/electron/tags",
        "blobs_url": "https://api.github.com/repos/electron/electron/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/electron/electron/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/electron/electron/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/electron/electron/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/electron/electron/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/electron/electron/languages",
        "stargazers_url": "https://api.github.com/repos/electron/electron/stargazers",
        "contributors_url": "https://api.github.com/repos/electron/electron/contributors",
        "subscribers_url": "https://api.github.com/repos/electron/electron/subscribers",
        "subscription_url": "https://api.github.com/repos/electron/electron/subscription",
        "commits_url": "https://api.github.com/repos/electron/electron/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/electron/electron/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/electron/electron/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/electron/electron/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/electron/electron/contents/{+path}",
        "compare_url": "https://api.github.com/repos/electron/electron/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/electron/electron/merges",
        "archive_url": "https://api.github.com/repos/electron/electron/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/electron/electron/downloads",
        "issues_url": "https://api.github.com/repos/electron/electron/issues{/number}",
        "pulls_url": "https://api.github.com/repos/electron/electron/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/electron/electron/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/electron/electron/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/electron/electron/labels{/name}",
        "releases_url": "https://api.github.com/repos/electron/electron/releases{/id}",
        "deployments_url": "https://api.github.com/repos/electron/electron/deployments",
        "created_at": "2013-04-12T01:47:36Z",
        "updated_at": "2024-01-13T06:11:42Z",
        "pushed_at": "2024-01-12T22:54:37Z",
        "git_url": "git://github.com/electron/electron.git",
        "ssh_url": "git@github.com:electron/electron.git",
        "clone_url": "https://github.com/electron/electron.git",
        "svn_url": "https://github.com/electron/electron",
        "homepage": "https://electronjs.org",
        "size": 141625,
        "stargazers_count": 110217,
        "watchers_count": 110217,
        "language": "C++",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 15447,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 904,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "c-plus-plus",
          "chrome",
          "css",
          "electron",
          "html",
          "javascript",
          "nodejs",
          "v8",
          "works-with-codespaces"
        ],
        "visibility": "public",
        "forks": 15447,
        "open_issues": 904,
        "watchers": 110217,
        "default_branch": "main",
        "score": 1.0
      }
    ]
  }